# Generated by Django 4.2.1 on 2023-05-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_rename_description_blog_blog_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogComment",
        ),
    ]
