# Generated by Django 4.2.1 on 2023-05-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
