# Generated by Django 4.2.1 on 2023-05-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
    ]
